### ISSUE TITLE
Do Symlinks work here?

### ISSUE THREAD

**Issue by aspauldingcode** [unmanbearpig/unmenu#4]
I'd like to launch obsidian, which I installed from nixpkgs.
Since nix just symlinks to nix store, I wanted to source my symlink directory for the user.

Under dirs = [] section, I added:

```
dirs = [
        "/System/Applications/",
        "/Applications/",
        "/System/Applications/Utilities/",
        "/System/Library/CoreServices/",
        "~/.unmenu-bin",
        "/nix/store/" # not how I should add nix store.. the bottom 2 are..
        "~/.nix-profile/bin/", # hmm...
		"/etc/profiles/per-user/alex/bin/", # not working?
        "/run/current-system/sw/bin/", # also not working?
      ]
```

What am I doing wrong?

btw the real package is located in the hashed longpath in filesystem under /nix/store as 

`/nix/store/5jjg88bvir8rrrj6bprwgsapd56s5yrf-home-manager-path/bin/obsidian`

So the best way is to just enable symlink support.. Does unmenu have this already?

**Comment by unmanbearpig** [comment]
Hey @aspauldingcode, try this release, it should be fixed now: https://github.com/unmanbearpig/unmenu/releases/tag/v0.2

**Comment by aspauldingcode** [comment]
Yes this works. 
Sorry for late response, had to restore my computer. 
Awesome!
