### ISSUE TITLE
Allow alt+d

### ISSUE THREAD

**Issue by aspauldingcode** [unmanbearpig/unmenu#6]
Idk if alt/option is working now at the moment but I'd like to use it.

**Comment by unmanbearpig** [comment]
@aspauldingcode you mean to delete the next word? Wouldn't it do nothing most of the time? Your cursor is at the end most of the time, right? Usually all alt key combos print weird characters on mac so I don't expect them to do something else unless it's the terminal. All ctrl keybindings work out of the box though, so I usually do ctrl-a ctrl-k when I want to delete the line and it works everywhere

**Comment by aspauldingcode** [comment]
Hey sorry.

I just tested it and it worked.
I was trying to use alt-d in my config a while ago but it didn't work because I broke my toml format. alt and d works. closing.... * oops *
